### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Devices.TheImagingSource#1]
- [x] VideoIn: "Fps" input -> "FPS"
- [x] VideoIn: too much info on the Info output (only keep first 3 lines)
- [x] FromFile -> ConfigReader, "File" input -> "File Path", add "Read" input, "Result" output -> "Output"
- [x] SaveConfigToFile -> ConfigWriter, "Path" input -> "File Path", "Save" input -> "Write", "Video In" input -> "Input"
- [x] PropertyInfo.Deconstruct -> "Split"
- [x] add to help patch: "For driver installation requirements, see: https://github.com/vvvv/VL.Devices.TheImagingSource?tab=readme-ov-file#getting-started"
- [x] On VideoIn node, have GetProperty/AvailableProperties nodes instead of spread of property infos

**Comment by azeno** [comment]
Deconstruct is what the auto generated method is called when defining a C# record. So this would be something we'd need to change on our end. Could obviously break some patches though... but shouldn't be that many yet. And records we will see more and more for sure.

**Comment by joreg** [comment]
- [x] VideoIn: defaults for resolution/fps should be: 640/480@30
- [x] VideoIn: make sure it doesn't crash with out-of-range resolution/fps
- [x] VideoIn: add "Enabled" input
- [x] AvailableProperties: alphabetically sort output
- [x] make IConfiguration advanced

**Comment by azeno** [comment]
@joreg The defaults will work in upcoming preview builds (https://github.com/devvvvs/vvvv/commit/7f25690525e0da1083678871110124620d74d663)
